# Railway Build Configuration
[build]
builder = "heroku/buildpacks:20"

[deploy]
startCommand = "npm start"
healthcheckPath = "/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
